### ISSUE TITLE
Error occurred intermittently  on stopping a broker

### ISSUE THREAD

**Issue by elon0823** [paust-team/shapleq#172]
### Issues
* cgo execution error occurred intermittently on only stopping a broker

```
signal arrived during cgo execution
instruction bytes: 0xf 0xb 0x66 0x2e 0xf 0x1f 0x84 0x0 0x0 0x0 0x0 0x0 0xf 0x1f 0x40 0x0

goroutine 459 [syscall]:
runtime.cgocall(0x4749b40, 0xc000090a70)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc000090a48 sp=0xc000090a10 pc=0x4008b5c
github.com/linxGnu/grocksdb._Cfunc_rocksdb_iter_seek(0x600000008010, 0xc0003b0810, 0x29)
	_cgo_gotypes.go:3008 +0x45 fp=0xc000090a70 sp=0xc000090a48 pc=0x4619fe5
github.com/linxGnu/grocksdb.(*Iterator).Seek.func1(0x0?, 0xc000090ad8?, {0xc0003b0810?, 0x29, 0xc000090ac0?})
	/Users/elenore/go/pkg/mod/github.com/linx!gnu/grocksdb@v1.6.45/iterator.go:99 +0x67 fp=0xc000090ab0 sp=0xc000090a70 pc=0x463b9a7
github.com/linxGnu/grocksdb.(*Iterator).Seek(0xc000090cb8?, {0xc0003b0810?, 0x20?, 0x0?})
	/Users/elenore/go/pkg/mod/github.com/linx!gnu/grocksdb@v1.6.45/iterator.go:99 +0x36 fp=0xc000090ae8 sp=0xc000090ab0 pc=0x463b8f6
github.com/paust-team/shapleq/broker/pipeline.(*FetchPipe).iterateRecords(0xc0004828a0, {0xc000522120, 0x1c}, 0x3c, 0x1, 0xc0005ef560, 0xc0005ef620)
	/Users/elenore/go/pkg/mod/github.com/paust-team/shapleq@v0.3.5/broker/pipeline/fetch_pipe.go:108 +0x4ec fp=0xc000090f50 sp=0xc000090ae8 pc=0x465ac4c
github.com/paust-team/shapleq/broker/pipeline.(*FetchPipe).Ready.func1.2({0xc000522120?, 0xc0000ef768?}, 0xc0000ef778?)
```

### Workarounds
* I'm not sure this is the right cause, but I found closing the rocksdb iterator is missed in the FetchPipe.

**Comment by elon0823** [comment]
I have not experienced this error after #173, #174 is merged.
Close this issue for now.
